/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateCategoriesRouteImport } from './routes/_private/categories'
import { Route as PrivateExpenseRouteImport } from './routes/_private/expense'
import { Route as PrivateIncomeRouteImport } from './routes/_private/income'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PrivateExpenseIndexRouteImport } from './routes/_private/expense.index'
import { Route as PrivateExpenseExpenseIdRouteImport } from './routes/_private/expense.$expenseId'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateCategoriesRoute = PrivateCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateExpenseRoute = PrivateExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateIncomeRoute = PrivateIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateExpenseIndexRoute = PrivateExpenseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateExpenseRoute,
} as any)
const PrivateExpenseExpenseIdRoute = PrivateExpenseExpenseIdRouteImport.update({
  id: '/$expenseId',
  path: '/$expenseId',
  getParentRoute: () => PrivateExpenseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/categories': typeof PrivateCategoriesRoute
  '/expense': typeof PrivateExpenseRouteWithChildren
  '/income': typeof PrivateIncomeRoute
  '/profile': typeof PrivateProfileRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/expense/$expenseId': typeof PrivateExpenseExpenseIdRoute
  '/expense/': typeof PrivateExpenseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/categories': typeof PrivateCategoriesRoute
  '/income': typeof PrivateIncomeRoute
  '/profile': typeof PrivateProfileRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/expense/$expenseId': typeof PrivateExpenseExpenseIdRoute
  '/expense': typeof PrivateExpenseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/categories': typeof PrivateCategoriesRoute
  '/_private/expense': typeof PrivateExpenseRouteWithChildren
  '/_private/income': typeof PrivateIncomeRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/expense/$expenseId': typeof PrivateExpenseExpenseIdRoute
  '/_private/expense/': typeof PrivateExpenseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/expense'
    | '/income'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/expense/$expenseId'
    | '/expense/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/income'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/expense/$expenseId'
    | '/expense'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/categories'
    | '/_private/expense'
    | '/_private/income'
    | '/_private/profile'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/register'
    | '/_private/'
    | '/_private/expense/$expenseId'
    | '/_private/expense/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/categories': {
      id: '/_private/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PrivateCategoriesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/expense': {
      id: '/_private/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof PrivateExpenseRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/income': {
      id: '/_private/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof PrivateIncomeRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/expense/': {
      id: '/_private/expense/'
      path: '/'
      fullPath: '/expense/'
      preLoaderRoute: typeof PrivateExpenseIndexRouteImport
      parentRoute: typeof PrivateExpenseRoute
    }
    '/_private/expense/$expenseId': {
      id: '/_private/expense/$expenseId'
      path: '/$expenseId'
      fullPath: '/expense/$expenseId'
      preLoaderRoute: typeof PrivateExpenseExpenseIdRouteImport
      parentRoute: typeof PrivateExpenseRoute
    }
  }
}

interface PrivateExpenseRouteChildren {
  PrivateExpenseExpenseIdRoute: typeof PrivateExpenseExpenseIdRoute
  PrivateExpenseIndexRoute: typeof PrivateExpenseIndexRoute
}

const PrivateExpenseRouteChildren: PrivateExpenseRouteChildren = {
  PrivateExpenseExpenseIdRoute: PrivateExpenseExpenseIdRoute,
  PrivateExpenseIndexRoute: PrivateExpenseIndexRoute,
}

const PrivateExpenseRouteWithChildren = PrivateExpenseRoute._addFileChildren(
  PrivateExpenseRouteChildren,
)

interface PrivateRouteChildren {
  PrivateCategoriesRoute: typeof PrivateCategoriesRoute
  PrivateExpenseRoute: typeof PrivateExpenseRouteWithChildren
  PrivateIncomeRoute: typeof PrivateIncomeRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateCategoriesRoute: PrivateCategoriesRoute,
  PrivateExpenseRoute: PrivateExpenseRouteWithChildren,
  PrivateIncomeRoute: PrivateIncomeRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
