/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateCategoriesRouteImport } from './routes/_private/categories'
import { Route as PrivateExpenseRouteImport } from './routes/_private/expense'
import { Route as PrivateIncomeRouteImport } from './routes/_private/income'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateUsersRouteImport } from './routes/_private/users'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PrivateCategoriesIndexRouteImport } from './routes/_private/categories.index'
import { Route as PrivateCategoriesCategoryIdRouteImport } from './routes/_private/categories.$categoryId'
import { Route as PrivateExpenseIndexRouteImport } from './routes/_private/expense.index'
import { Route as PrivateExpenseExpenseIdRouteImport } from './routes/_private/expense.$expenseId'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateCategoriesRoute = PrivateCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateExpenseRoute = PrivateExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateIncomeRoute = PrivateIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateUsersRoute = PrivateUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateCategoriesIndexRoute = PrivateCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateCategoriesRoute,
} as any)
const PrivateCategoriesCategoryIdRoute =
  PrivateCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => PrivateCategoriesRoute,
  } as any)
const PrivateExpenseIndexRoute = PrivateExpenseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateExpenseRoute,
} as any)
const PrivateExpenseExpenseIdRoute = PrivateExpenseExpenseIdRouteImport.update({
  id: '/$expenseId',
  path: '/$expenseId',
  getParentRoute: () => PrivateExpenseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/categories': typeof PrivateCategoriesRouteWithChildren
  '/expense': typeof PrivateExpenseRouteWithChildren
  '/income': typeof PrivateIncomeRoute
  '/profile': typeof PrivateProfileRoute
  '/users': typeof PrivateUsersRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/categories/$categoryId': typeof PrivateCategoriesCategoryIdRoute
  '/expense/$expenseId': typeof PrivateExpenseExpenseIdRoute
  '/categories/': typeof PrivateCategoriesIndexRoute
  '/expense/': typeof PrivateExpenseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/income': typeof PrivateIncomeRoute
  '/profile': typeof PrivateProfileRoute
  '/users': typeof PrivateUsersRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/categories/$categoryId': typeof PrivateCategoriesCategoryIdRoute
  '/expense/$expenseId': typeof PrivateExpenseExpenseIdRoute
  '/categories': typeof PrivateCategoriesIndexRoute
  '/expense': typeof PrivateExpenseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/categories': typeof PrivateCategoriesRouteWithChildren
  '/_private/expense': typeof PrivateExpenseRouteWithChildren
  '/_private/income': typeof PrivateIncomeRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/users': typeof PrivateUsersRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/categories/$categoryId': typeof PrivateCategoriesCategoryIdRoute
  '/_private/expense/$expenseId': typeof PrivateExpenseExpenseIdRoute
  '/_private/categories/': typeof PrivateCategoriesIndexRoute
  '/_private/expense/': typeof PrivateExpenseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/expense'
    | '/income'
    | '/profile'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/categories/$categoryId'
    | '/expense/$expenseId'
    | '/categories/'
    | '/expense/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/income'
    | '/profile'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/categories/$categoryId'
    | '/expense/$expenseId'
    | '/categories'
    | '/expense'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/categories'
    | '/_private/expense'
    | '/_private/income'
    | '/_private/profile'
    | '/_private/users'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/register'
    | '/_public/reset-password'
    | '/_private/'
    | '/_private/categories/$categoryId'
    | '/_private/expense/$expenseId'
    | '/_private/categories/'
    | '/_private/expense/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/categories': {
      id: '/_private/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PrivateCategoriesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/expense': {
      id: '/_private/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof PrivateExpenseRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/income': {
      id: '/_private/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof PrivateIncomeRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/users': {
      id: '/_private/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/categories/': {
      id: '/_private/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof PrivateCategoriesIndexRouteImport
      parentRoute: typeof PrivateCategoriesRoute
    }
    '/_private/categories/$categoryId': {
      id: '/_private/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof PrivateCategoriesCategoryIdRouteImport
      parentRoute: typeof PrivateCategoriesRoute
    }
    '/_private/expense/': {
      id: '/_private/expense/'
      path: '/'
      fullPath: '/expense/'
      preLoaderRoute: typeof PrivateExpenseIndexRouteImport
      parentRoute: typeof PrivateExpenseRoute
    }
    '/_private/expense/$expenseId': {
      id: '/_private/expense/$expenseId'
      path: '/$expenseId'
      fullPath: '/expense/$expenseId'
      preLoaderRoute: typeof PrivateExpenseExpenseIdRouteImport
      parentRoute: typeof PrivateExpenseRoute
    }
  }
}

interface PrivateCategoriesRouteChildren {
  PrivateCategoriesCategoryIdRoute: typeof PrivateCategoriesCategoryIdRoute
  PrivateCategoriesIndexRoute: typeof PrivateCategoriesIndexRoute
}

const PrivateCategoriesRouteChildren: PrivateCategoriesRouteChildren = {
  PrivateCategoriesCategoryIdRoute: PrivateCategoriesCategoryIdRoute,
  PrivateCategoriesIndexRoute: PrivateCategoriesIndexRoute,
}

const PrivateCategoriesRouteWithChildren =
  PrivateCategoriesRoute._addFileChildren(PrivateCategoriesRouteChildren)

interface PrivateExpenseRouteChildren {
  PrivateExpenseExpenseIdRoute: typeof PrivateExpenseExpenseIdRoute
  PrivateExpenseIndexRoute: typeof PrivateExpenseIndexRoute
}

const PrivateExpenseRouteChildren: PrivateExpenseRouteChildren = {
  PrivateExpenseExpenseIdRoute: PrivateExpenseExpenseIdRoute,
  PrivateExpenseIndexRoute: PrivateExpenseIndexRoute,
}

const PrivateExpenseRouteWithChildren = PrivateExpenseRoute._addFileChildren(
  PrivateExpenseRouteChildren,
)

interface PrivateRouteChildren {
  PrivateCategoriesRoute: typeof PrivateCategoriesRouteWithChildren
  PrivateExpenseRoute: typeof PrivateExpenseRouteWithChildren
  PrivateIncomeRoute: typeof PrivateIncomeRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateUsersRoute: typeof PrivateUsersRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateCategoriesRoute: PrivateCategoriesRouteWithChildren,
  PrivateExpenseRoute: PrivateExpenseRouteWithChildren,
  PrivateIncomeRoute: PrivateIncomeRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateUsersRoute: PrivateUsersRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
